# Generated by Django 2.0.1 on 2018-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180125_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='citystatezip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
